added live url at the end

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -205,9 +205,23 @@ jobs:
             --set image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/spacecapybara_app \
             --set image.tag=1.0.${{ github.run_number }} \
             --atomic
+        # --atomic flag for auto-rollback if helm deployment did't succeed. Gotta add a FAILURE CHECK here and if helm upgrade really didn't work, then catch that in the workflow and fail the whole pipeline with a proper message.
 
       # - name: Deploy to GKE
       #   run: |
       #     kubectl apply -f k8sDeployment.yaml
-      #     helm install 
         # kubectl rollout status deployment/k8sdeployment -n YOUR_NAMESPACE
+
+      - name: Get External IP of Space Capybara Service
+        run: |
+          echo "Waiting for external IP..."
+          for i in {1..10}; do
+            EXTERNAL_IP=$(kubectl get svc space-capybara-web --namespace default --output=jsonpath='{.status.loadBalancer.ingress[0].ip}')
+            if [ -n "$EXTERNAL_IP" ]; then
+              echo "Space capy running at: http://$EXTERNAL_IP:5002"
+              exit 0
+            fi
+            echo "Waiting for LoadBalancer IP to be assigned... ($i/10)"
+            sleep 10
+          done
+          echo "❌ ERROR: Timed out waiting for external IP!" && exit 1
